#!/bin/bash

msg="+++"
push=0
args=()

while [ $# -gt 0 ]; do
  case "$1" in
    -m)
      if [ -z "$2" ]; then
        echo "Error: -m requires a message argument"
        exit 1
      fi
      msg="$2"
      shift 2
      ;;
    push)
      push=1
      shift
      ;;
    *)
      args+=("$1")
      shift
      ;;
  esac
done

untracked=$(git status | grep 'Untracked files' | wc -l)
unstaged=$(git status | grep 'Changes not staged for commit' | wc -l)

if [ $untracked -gt 0 ] || [ $unstaged -gt 0 ]; then
  git add -A
  git commit -m "$msg"
else
  echo "Nothing to commit, working tree clean."
fi

if [ $push -eq 1 ]; then
  git push
fi

git log

